### ISSUE TITLE
diagnostics from non-lsp: linters

### ISSUE THREAD

**Issue by mathjiajia** [brianaung/yasl.nvim#5]
https://github.com/brianaung/yasl.nvim/blob/6c37bd4728f728474c223e61203dd0c938ccfee2/lua/yasl/builtins/diagnostics.lua#L16-L18

this lines of code block linters

**Comment by brianaung** [comment]
Hey there!

I tried to reproduce the error using this minimal config with [none-ls linter](https://github.com/nvimtools/none-ls.nvim) but could not replicate it.
```lua
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
    vim.fn.system {
        "git",
        "clone",
        "--filter=blob:none",
        "https://github.com/folke/lazy.nvim.git",
        "--branch=stable",
        lazypath,
    }
end
vim.opt.rtp:prepend(lazypath)

require("lazy").setup {
    {
        "nvimtools/none-ls.nvim",
        dependencies = {
            "nvim-lua/plenary.nvim",
        },
        config = function()
            local null_ls = require("null-ls")
            null_ls.setup {
                sources = {
                    null_ls.builtins.diagnostics.selene,
                },
            }
        end,
    },
    {
        "brianaung/yasl.nvim",
        config = function()
            require("yasl").setup {
                enable_icons = true,
            }
        end,
    },
}
```

Which linter are you using? Can you provide me a bit more info so I can look into this further?

**Comment by brianaung** [comment]
My guess is that the linter you use does not attach to lsp (unlike none-ls), that's why it was not working.

The specific check for copilot client shouldn't be needed anymore (I used to display different status for LSP "OFF"/active but copilot was messing with it, but that's no longer the case). But I still would like to prevent unnecessarily calling the rest of the functions when there are no clients attached.

**Comment by mathjiajia** [comment]
yes, I am using https://github.com/mfussenegger/nvim-lint so any diagnostics from the linter will not be displayed on the statusline.

**Comment by brianaung** [comment]
Hey the fix has been merged.

I have tested it and it works. let me know if the error still persists.

**Comment by mathjiajia** [comment]
it works fine, thank you.
